#base image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

#copy .txt file to working directory
COPY ./requirements.txt .

#install dependencies that are needed
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the client-side code into the container at /app
COPY ../app/client.py .

#command that's run when the container starts
CMD [ "python", "client.py" ]
