#base image
FROM python:3.9

#working directory set
WORKDIR /app

#copy .txt file to working directory
COPY ./requirements.txt .

#install dependencies that are needed
RUN pip install --no-cache-dir -r requirements.txt

#copy client.py to working directory
COPY ../app/client.py .

#command that's run when the container starts
CMD [ "python", "client.py" ]
