version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000" #server listening on port 5000

  client:
    build:
      context: ./client
    depends_on: #Ensure server is built and ran before the client
      - server
