#base image
FROM python:3.9 

#working directory set
WORKDIR /app

#copy .txt file to working directory
COPY requirements.txt .

#install dependencies that are needed
RUN pip install --no-cache-dir -r requirements.txt

#copy server.py to working directory
COPY server.py .

#expose the port we need for the server
EXPOSE 5000

#command that's run when the container starts
CMD ["python", "server.py"]